# Generated by Django 4.1.3 on 2023-09-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementtempsreel',
            name='numero_semaine',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
